name: Publish docs via GitHub Pages

# 触发条件
on:
   push:
     branches:
       - main
   pull_request:
     branches:
       - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest  # 修改为 Ubuntu 环境
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if (Test-Path -Path $env:REQUIREMENTS) {
            pip install -r $env:REQUIREMENTS
          }
        shell: pwsh     # 使用 PowerShell
        env:
          EXTRA_PACKAGES: build-base
          REQUIREMENTS: requirements.txt

      - name: Deploy MkDocs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.26
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EXTRA_PACKAGES: build-base
          REQUIREMENTS: requirements.txt
